### ISSUE TITLE
Bulding the map 2) State x Assignment -> RV truth Value

### ISSUE THREAD

**Issue by RiccardoDeMasellis** [RiccardoDeMasellis/First-order-LTL-monitoring#12]
This is hard as it requires to implement the reachability algorithm. The algorithm should work as follows: given a state and an assignment, it returns the set of reachable states. I suggest the fixpoint algorithm:
First step: result = initial state
General iteration:  result = result UNION states reachable in one step from states in result. For this it helps the map 2) of the executable automaton.
END when results remain the same from one iteration to the other.

Then, depending on the kind of states in result, establish the RV truth value of the input state for the input assignment.

**Comment by simoneclr** [comment]
#15
